### ISSUE TITLE
Disassociate from parent fork (or swap who's parent)

### ISSUE THREAD

**Issue by duttonw** [qld-gov-au/ckanext-ytp-comments#79]
Per  https://github.com/vrk-kpa/ckanext-ytp-comments/issues/14#issuecomment-1195057350

Seems we may be the primary now.

Should we request Github support to disconnect or swap association

**Comment by ThrawnCA** [comment]
Well, reviewing other forks at https://github.com/vrk-kpa/ckanext-ytp-comments/network/members suggests that there aren't really any other candidates for primary. They just have a few extra commits, or sometimes they're not even up to date. Keitaro hasn't forked this one, apparently.

However, I'm not sure there's any benefit from disconnecting. It would become harder for the other forks to merge our changes, since GitHub would no longer know that they're related, and we would be less discoverable. What would we gain?

If we can become the new parent, that might work, although I would imagine it would require agreement from existing forks.

**Comment by duttonw** [comment]
Raised Ticket 3112548 to switch up forks.

**Comment by duttonw** [comment]
This is now completed

**Comment by ThrawnCA** [comment]
Looks like the link was broken, but not reversed. So we are not considered the parent of the other forks.
